### ISSUE TITLE
[Error] Expected a type

### ISSUE THREAD

**Issue by masbrodin** [portsip/portsip-softphone-ios#2]
I tried to build in xcode 11.7 an error message appeared,like this : 

> In file included from Pods/JRDB/JRDB/JRDB/JRDB.h:23:
> In file included from Pods/JRDB/JRDB/JRDB/JRDBChain.h:14:
> Pods/JRDB/JRDB/JRDB/JRDBChainCondition.h:45:76: error: expected a type
> @property (nonatomic, assign, readonly) JRDBChainConditionOperator operator;
>                                                                            ^
> Pods/JRDB/JRDB/JRDB/JRDBChainCondition.h:45:1: error: property requires fields to be named
> @property (nonatomic, assign, readonly) JRDBChainConditionOperator operator;
> ^                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~
> /Users/artemist/Documents/iOS/portsip-softphone-ios/PortGo/PortGo/Others/AppDelegate.mm:1623:1: warning: implementing deprecated method [-Wdeprecated-implementations]
> - (void)alertView:(UIAlertView *)alertView
> 

are there any details for this build in xcode 11.7 and ios 13.7 version?
